# Stubs for msvcrt

from typing import overload, BinaryIO, TextIO

def locking(handle: int, mode: int, nbytes: int) -> None: ...
def set_mode(fd: int, flags: int) -> None: ...
def get_osfhandle(file: int) -> int: ...
def open_osfhandle(handle: int, flags: int) -> int: ...
def kbhit() -> bool: ...
def getch() -> int: ...
def getwch() -> int: ...
def getche() -> int: ...
def getwche() -> int: ...
def putch(int) -> None: ...
def putwch(int) -> None: ...
def ungetch(int) -> None: ...
def ungetwch(int) -> None: ...
def heapmin() -> None: ...
